namespace SistemaBico.Web.Util
{
    public class ListGeneric
    {
        public static List<string> GetProfessionalEspeciality()
        {
            List<string> list = new List<string>();
            list.Add("Assistência Adega Climatizada");
            list.Add("Assistência Aparelho de Som");
            list.Add("Assistência Aparelhos de Ginástica");
            list.Add("Assistência Aquecedor a Gás");
            list.Add("Assistência Ar condicionado");
            list.Add("Assistência Cabeamento e Redes");
            list.Add("Assistência Celular");
            list.Add("Assistência Computador/Notebook");
            list.Add("Assistência Cortador de Grama");
            list.Add("Assistência Câmera");
            list.Add("Assistência Eletrodomésticos");
            list.Add("Assistência Fogão e cooktop");
            list.Add("Assistência Fone de Ouvido");
            list.Add("Assistência Geladeira e freezer");
            list.Add("Assistência Gerador");
            list.Add("Assistência Home theater");
            list.Add("Assistência Impressora");
            list.Add("Assistência Instrumentos Musicais");
            list.Add("Assistência Lava Louça");
            list.Add("Assistência Lava roupa");
            list.Add("Assistência Micro-ondas");
            list.Add("Assistência Notebooks e Laptops");
            list.Add("Assistência Relógios");
            list.Add("Assistência Secadora de Roupas");
            list.Add("Assistência Smartwatch");
            list.Add("Assistência Tablet");
            list.Add("Assistência Televisão");
            list.Add("Assistência Vídeo game");
            list.Add("Aulas Artes");
            list.Add("Aulas Artesanato");
            list.Add("Aulas Desenvolvimento Web");
            list.Add("Aulas Escolares e Reforço<");
            list.Add("Aulas Esportes Eletrônicos");
            list.Add("Aulas Fotografia");
            list.Add("Aulas Gastronomia");
            list.Add("Aulas Idiomas");
            list.Add("Aulas Informática");
            list.Add("Aulas Luta");
            list.Add("Aulas Marketing Digital");
            list.Add("Aulas Moda");
            list.Add("Aulas Música");
            list.Add("Aulas Paisagismo");
            list.Add("Aulas Saúde");
            list.Add("Aulas TV e Teatro");
            list.Add("Alarme");
            list.Add("Ar Condicionado Automotivo");
            list.Add("Auto elétrico<");
            list.Add("Borracharia");
            list.Add("Funilaria Automotiva");
            list.Add("Guincho");
            list.Add("Higienização e Polimento");
            list.Add("Insulfilm");
            list.Add("Martelinho de Ouro");
            list.Add("Mecânica Geral");
            list.Add("Pintura");
            list.Add("Som Automotivo");
            list.Add("Venda de Automóveis");
            list.Add("Vidraçaria Automotiva");
            list.Add("Administração de Condomínios");
            list.Add("Administração de Imóveis");
            list.Add("Advogado");
            list.Add("Assessor de Investimentos");
            list.Add("Assessoria de Imprensa");
            list.Add("Auditoria e Assuntos Regulatórios");
            list.Add("Auxilio administrativo");
            list.Add("Consultor pessoal");
            list.Add("Contador");
            list.Add("Corretor");
            list.Add("Despachante");
            list.Add("Detetive Particular");
            list.Add("Digitação e Digitalização de Documentos");
            list.Add("Economia e Finanças");
            list.Add("Escrita e Conteúdo");
            list.Add("Guia de Turismo");
            list.Add("Mediação de Conflitos");
            list.Add("Palestrantes");
            list.Add("Pesquisas em geral");
            list.Add("Produção, padronização e revisão de conteúdo");
            list.Add("Recrutamento e Seleção");
            list.Add("Segurança do Trabalho");
            list.Add("Testamento e Planejamento Patrimonial");
            list.Add("Tradução");
            list.Add("Tradução Juramentada");
            list.Add("Treinamentos");
            list.Add("Animação (Motion)");
            list.Add("Aplicativos para celular e redes sociais");
            list.Add("Autocad e Modelagem 3D");
            list.Add("Convites");
            list.Add("Corte e Gravação a Laser");
            list.Add("Criação de Logos");
            list.Add("Criação de Marca");
            list.Add("Desenvolvimento de Game");
            list.Add("Desenvolvimento de Sites e Sistemas");
            list.Add("Diagramador");
            list.Add("Edição de Foto");
            list.Add("Ilustração");
            list.Add("Marketing Online");
            list.Add("Materiais promocionais");
            list.Add("Panfletagem");
            list.Add("Produção gráfica");
            list.Add("Restauração de Fotos");
            list.Add("Serviços de TI07");
            list.Add("Soluções em Streaming");
            list.Add("Ilustração");
            list.Add("Ux - Ui Design");
            list.Add("Web Design");
            list.Add("Áudio e Vídeo");
            list.Add("Outro");
            list.Add("Animação de Festas");
            list.Add("Assessor de Eventos");
            list.Add("Bandas e cantores");
            list.Add("Bartenders");
            list.Add("Brindes e Lembrancinhas");
            list.Add("Buffet Completo");
            list.Add("Carros de Casamento");
            list.Add("Casting para Eventos");
            list.Add("Celebrantes");
            list.Add("Chocolateiro");
            list.Add("Churrasqueiro24");
            list.Add("Confeitaria");
            list.Add("Decoração");
            list.Add("Djs");
            list.Add("quipamentos para festas");
            list.Add("Florista");
            list.Add("Food Truck");
            list.Add("Fotografia");
            list.Add("Garçons e Copeiras");
            list.Add("Gravação de Vídeos");
            list.Add("Manobrista");
            list.Add("Organização de Eventos");
            list.Add("Personal Chef");
            list.Add("Recepcionistas e Cerimonialistas");
            list.Add("Segurança");
            list.Add("Sommelier");
            list.Add("Ônibus Balada");
            list.Add("Alfaiate");
            list.Add("Artesanato");
            list.Add("Barbeiro");
            list.Add("Bronzeamento");
            list.Add("Cabeleireiros");
            list.Add("Corte e costura");
            list.Add("Depilação");
            list.Add("Designer de Cílios");
            list.Add("Designer de Sobrancelhas");
            list.Add("Esotérico");
            list.Add("Esteticista");
            list.Add("Manicure e pedicure");
            list.Add("Maquiadores");
            list.Add("Micropigmentador");
            list.Add("Ourives");
            list.Add("Personal Stylist");
            list.Add("Podólogo");
            list.Add("Sapateiro");
            list.Add("Visagista");
            list.Add("Afiação");
            list.Add("Agrimensura");
            list.Add("Aluguel de Grandes Equipamentos de Construção");
            list.Add("Aluguel de Maquinário");
            list.Add("Antenista");
            list.Add("Análises Ambientais");
            list.Add("Arquiteto");
            list.Add("Automação Residencial");
            list.Add("Banheira");
            list.Add("Casas e Chalés de Madeira");
            list.Add("Chaveiro");
            list.Add("Climatização");
            list.Add("Coifas e Exaustores");
            list.Add("Concretagem");
            list.Add("Decorador");
            list.Add("Dedetizador");
            list.Add("Demolição");
            list.Add("Desentupidor");
            list.Add("Banheira");
            list.Add("Design de Interiores");
            list.Add("Desinfecção");
            list.Add("Dutos");
            list.Add("Eletricista");
            list.Add("Empreiteiro");
            list.Add("Encanador");
            list.Add("Energia Solar");
            list.Add("Engenheiro");
            list.Add("Escada, Corrimão e Guarda-Corpo");
            list.Add("Fossa");
            list.Add("Galvanização");
            list.Add("Gesso e DryWall");
            list.Add("Gás");
            list.Add("Escavação");
            list.Add("Impermeabilizador");
            list.Add("Instalador TV Digital");
            list.Add("Instalação de eletrônicos");
            list.Add("Instalação de Papel de Parede");
            list.Add("Isolamentos Térmico e Acústico");
            list.Add("Jardinagem");
            list.Add("Lareira");
            list.Add("Lazer e Recreação");
            list.Add("Limpeza de Vidros");
            list.Add("Limpeza Pós Obra");
            list.Add("Marceneiro");
            list.Add("Marido de aluguel");
            list.Add("Marmoraria e Granitos");
            list.Add("Montador de Móveis");
            list.Add("Mudanças e Carretos");
            list.Add("Paisagista");
            list.Add("Pavimentação");
            list.Add("Pedreiro");
            list.Add("Pintor");
            list.Add("Piscina");
            list.Add("Portão Automático");
            list.Add("Poço Artesiano");
            list.Add("Prevenção e Combate a Incêndio");
            list.Add("Reciclagem");
            list.Add("Redes de Proteção");
            list.Add("Remoção de Entulho");
            list.Add("Restauração e Polimento de Pisos");
            list.Add("Segurança Eletrônica");
            list.Add("Segurança Perimetral");
            list.Add("Serralheria e Solda");
            list.Add("Sonorização de Ambientes");
            list.Add("Tapeceiro");
            list.Add("Terraplanagem");
            list.Add("Toldos e Coberturas");
            list.Add("Topografia");
            list.Add("Vidraceiro");
            list.Add("Aconselhamento Conjugal e Familiar");
            list.Add("Biomedicina Estética");
            list.Add("Coach");
            list.Add("Cuidador de Pessoas");
            list.Add("Dentista");
            list.Add("Enfermeira");
            list.Add("Fisioterapeuta");
            list.Add("Fonoaudiólogo");
            list.Add("Hipnoterapia");
            list.Add("Médico");
            list.Add("Nutricionista");
            list.Add("Psicanalista");
            list.Add("Psicólogo");
            list.Add("Quiropraxia");
            list.Add("Remoção de Tatuagem");
            list.Add("Terapia Ocupacional");
            list.Add("Terapias Alternativas");
            list.Add("Adestrador de Cães");
            list.Add("Babá");
            list.Add("Cozinheira");
            list.Add("Diarista");
            list.Add("Governanta");
            list.Add("Lavadeira");
            list.Add("Lavagem de Cortinas, Persianas e Tapetes");
            list.Add("Limpeza de Carpetes");
            list.Add("Limpeza de Piscina");
            list.Add("Motorista");
            list.Add("Passadeira");
            list.Add("Passeador de Cães");
            list.Add("Personal Organizer");
            list.Add("Personal Shopper");
            list.Add("Segurança Particular");
            list.Add("Segurança Patrimonial");
            list.Add("Serviços para Pets");

            return list;
        }
        public static List<string> GetProfessionalDynamicEspeciality(List<string> Especiality)
        {
            var especialityDefault = GetProfessionalEspeciality();
            return Especiality.Where(p => especialityDefault.All(p2 => p2 != p)).ToList();
           
        }
    }
}
